module Finance.OpenSymbology.PricingSourceDescriptions where
data Description =
    AssetMatchMTF
  | AthensExchangeAlternativeMarket
  | RBSHKAndKRGovernmentBonds
  | RBSIstanbul
  | RBSAustralia
  | ScotiabankColombia
  | RBSSingapore
  | RBSKazakhstan
  | RBSWholesale
  | TadawulSaudiArabiaStockExchange
  | AgriculturalBankofChinaCNYBonds
  | AgriculturalBankofChinaCNYOnshoreIRSAndFX
  | AmanahButlerBerhadMalaysia
  | RBSMumbai
  | RBSINRFX
  | RBSAsia
  | RBS
  | RBSJakarta
  | ANZBankTaiwanMoneyMarketRatesAndIRS
  | RBSAmsterdamIRSSwaps
  | AbsaBank
  | RBSSydney
  | ACEDerivativesandCommodityExchangeIndia
  | AFPConfia
  | Andorra
  | AdamantCapitalPartners
  | CreditSuisseEuropeanRates
  | BolsadeComerciodeBuenosAiresArgentinaStockExchangeFloor
  | AFETTheAgriculturalFuturesExchangeofThailand
  | AustralianFinancialMarketsAssociation
  | AmstelFinancialServicesPHPCurrencyProducts
  | AgriculturalBankofChina
  | ChiXAustralia
  | Anguilla
  | AIAF
  | AlliedIrishBankForwards
  | AlliedIrishBankDeposits
  | ArabJordanInvestmentBank
  | AkbankTASFXRates
  | AkbankTASOptionVolatilitiesAndDepositRates
  | AkbankTASFXNewRates
  | AustraliaComposite
  | BancaAletti
  | MercadodeValoresdeMendozaArgentina
  | NASDAQOMXArmenia
  | AutoridadeMonetariaDeMacauInterbankMiddleRates
  | AminvestmentBank
  | AmstelSecurities
  | LMELondonMetalExchange
  | AmbankGroup
  | AmstelFinancialServices
  | MTSNetherlands
  | Andima
  | AndimaIndicative
  | ICAPAsianNDFs
  | AndimaMinAndMax
  | BancoSantanderDepositsAndCDs
  | ANZBankFRASOISSwaps
  | ANZBankAustraliaAndNewZealandCurrencyPricing
  | ANZBankEuroMediumTermNotes
  | ANZBankJakartaMoneyMarketRates
  | ANZBankCNYAndCNHFXRates
  | ANZBankVietnamFXAndForwardRates
  | NSXNationalStockExchangeofAustralia
  | ASXPurematch
  | ArgentinaComposite
  | Meliorbanca
  | SIFGarbanArgentina
  | ICAPBrazil
  | AthensStockExchange
  | ASXAustralianSecuritiesExchangePitSession
  | ASXAustralianSecuritiesExchange
  | ASXAustralianSecuritiesExchangeAndAustraliaComposite
  | AurigaGlobalInvestors
  | RaiffeisenBankAval
  | ASXAustralianSecuritiesExchangeASX24
  | ANZBankCNYFX
  | ANZBankAsiaFX
  | ANZBankCorporateandGovernmentBonds
  | AllianzZBdooCroatia
  | BSEBarbadosStockExchange
  | UniCreditGroup
  | BankofAmericaMerrillLynch
  | BankofAmericaMerrillLynchINRFXRates
  | BankofAmericaMerrillLynchSingaporeGovernmentBonds
  | BarclaysCapital
  | BCBABolsadeComerciodeBuenosAires
  | BolsadeComerciodeBuenosAiresFloor
  | BancaAkros
  | BankaKombetare
  | UniCreditBankaSlovenijadd
  | BankofAmericaMerrillLynchAustralia
  | BankofAmericaMerrillLynchUSTreasuriesStripsTIPS
  | JPMorganChaseStructuredProductsLatAm
  | BanifInvestmentBankBrazilianandMexicanBonds
  | BankofAmericaMerrillLynchTreasuryMarkets
  | BankofAmericaMerrillLynchCorporateandGovernmentBonds
  | NYSEEuronextBrussels
  | JapanBondTradingCompany
  | JapanBondTradingCompany3pmpricing
  | BarclaysCapitalAsiaNY
  | BBVAChile
  | BarclaysCapitalSingapore
  | JapanBondTradingCompanyrealtime
  | BarclaysCapitalMoscow
  | BBSecurities
  | BloombergBondtrader
  | BBVA
  | BBVAInflationProducts
  | BBVAUruguayBonds
  | BloombergJPYenBondsFixingPrice
  | BloombergJPYenBondsYield
  | BourseRegionaledesValeursMobilieresBRVM
  | BolsadeComercioBuenosAiresBCBA
  | BVCBolsadeValoresdeColombia
  | BVCBolsadeValoresdeColombiaMEC
  | BolsadeComerciodeSantiagodeChile
  | BankofBeijing
  | BolsaComerciodeChile
  | BanqueEtCaisseDEpargneDeLEtatLuxembourg
  | BankofChina
  | IntesaSanpaolo
  | BarclaysCapitalTokyo
  | BarclaysCapitalJapanindicative
  | BankofCommunicationsHKCNHSpotAndFWD
  | BankofCommunications
  | BloombergComposite
  | BBVABancomer
  | BCPSecuritiesLLCEmergingMarketsDebtPricing
  | BCPSecuritiesLLCConvertibles
  | BancaComercialaRomanaFXRates
  | BCBABolsadeComerciodeBuenosAiresContinuedUS
  | CentralBankofVenezuela
  | BCVBanqueCantonaleVaudoise
  | DhakaStockExchange
  | BancodeChile
  | BanqueduLibanTheCentralBankofLebanon
  | BDOBancoDeOro
  | BeirutStockExchange
  | BelgradeStockExchange
  | BarclaysCapitalBRLDebentures
  | BEVSAUruguayElectronicStockExchange
  | BankforInternationalSettlement
  | BloombergFixing
  | BankForum
  | BCBABolsadeComerciodeBuenosAiresFloorUS
  | BFXBahrainFinancialExchange
  | BotswanaStockExchangeAndBotswanaComposite
  | BGCPartnersAsia
  | BGCPartnersUK
  | BGCantorFX
  | BloombergGenericPricing
  | BloombergGenericPricingChina
  | BloombergGenericPricingLondon
  | BloombergGenericPricingIndonesia
  | BloombergGenericPricingSingapore
  | BloombergGenericPricingTokyo
  | BGCPartners
  | BSXBermudaStockExchangeAndBermudaComposite
  | ICAPUKGilts
  | BGCantorDepoRates
  | BankHandlowywWarszawie
  | BahrainBourseAndBahrainComposite
  | BursaMalaysiaETP
  | BancoItauBrazil
  | BancoItauBrazilBonds
  | INGBelgium
  | BanjaLukaStockExchangeAndBanjaLukaComposite
  | BrÃ¼llKalmusBank
  | AltaeBancoPrivadoSA
  | BankofNewYork
  | BloombergFXCalculatedPricing
  | BBGCurrencySynthetics
  | BanqueLibanoFrancaise
  | BanjaLukaStockExchange
  | BanqueDeLuxembourgStructuredProducts
  | BISXBahamasInternationalSecuritiesExchange
  | JohannesburgStockExchangecontributedprices
  | BMCEBank
  | BMOBankofMontreal
  | BMFBrazilianMercantileandFuturesExchange
  | BMFBrazilianMercantileandFuturesExchangeTPlus1Settlement
  | BMFBrazilianMercantileandFuturesExchangeTPlus2Settlement
  | BMFBrazilianMercantileandFuturesExchangeFixing
  | BMFBrazilianMercantileandFuturesExchangeUSDOptionVolatities
  | BankofAmericaMerrillLynchLatAmUSDCorporates
  | BankofAmericaMerrillLynchCEEMEAOfferings
  | BankofAmericaMerrillLynchBMLTLatamFIPricing
  | BMONesbittBurns
  | BMOBankofMontrealCapitalCanadianGovernmentBonds
  | BMOBankofMontrealCapitalCanadianUSGovernmentBonds
  | BMOBankofMontrealInterestRateNotes
  | BMOBankofMontrealTreasuries
  | BankofAmericaMerrillLynchStructuredProductNotes
  | MTSBelgiumTreasuryBillsAndGovernmentBonds
  | BancoDeLaNacionArgentinaSpotandNDF
  | BNPParibasBangkokTHBSpotsandForwardRates
  | BolsaNacionaldeValoresCostaRicaGovtsCorps
  | BolsaNacionaldeValoresCostaRicaFXRates
  | BNPParibasCertificatesAndWarrants
  | BanamexBancoNacionaldeMexico
  | BNPParibasSingapore
  | BNPParibasCertificates
  | BNPParibasFixedIncomeAndSpotForwardandDepoFXRates
  | BNPParibas
  | BNPParibasPreciousMetals
  | BNPParibasEgypt
  | BNPParibasIndia
  | BNPParibasLatAm
  | BNPParibasTaiwan
  | BNPParibasCairo
  | ScotiaCapitalCADForwardRates
  | BankofNovaScotiaHKCNHDepositRates
  | ScotiaCapitalJamaicanGovernmentBondsFXAndRepos
  | ScotiaCapitalCoreEurogovernmentBonds
  | BNPParibasVietnam
  | BankofNewZealand
  | BMAndFBOVESPASomaSociedadeOperadoradoMercadodeAtivos
  | BankofAmericaMerrillLynchThailand
  | BankofAmericaMerrillLynchFXRates
  | BankofAmericaMerrillLynchSingapore
  | BankofAmericaMerrillLynchJakartaInterbankOfferRates
  | BankofAmericaMerrillLynchINRGovernmentBonds
  | BankofAmericaMerrillLynchFXStreaming
  | BankofAmericaMerrillLynchTaiwan
  | BankofChinaHK
  | BankofChinaChinaBenchmarkBonds
  | BankofChinaHKFixedIncomeAndFXDepositHIBORRates
  | ChinaBondBankofChinaBondPrices
  | BankofIreland
  | BankofIsraelForeignExchangeRates
  | BankofIrelandFiduciaryDepositRates
  | BankofKoreaFXandMoneyMarketRates
  | BankofShanghaiChinaBenchmarkBonds
  | BankofTokyoMitsubishiUFJ
  | BNPParibasNY
  | BNPParibasAsiaBondsandSwapsAndFX
  | BNPParibasAustralianGovernmentBonds
  | BNPParibasAsiaPacConvertibleBonds
  | BNPParibasCNHRates
  | BNPParibasQatar
  | BNPParibasSovereignAgenciesSupras
  | BNPParibasLondon
  | BPHBankPrzemyslowo
  | BPIBankofthePhilippineIslands
  | BNPParibasMYRFX
  | BNPParibasMoscow
  | BNPParibasNewIssues
  | BNPParibasUK
  | BNPParibasCNYSwapsandForwards
  | BNPParibasINRSwapsandForwards
  | EquiductTrading
  | BRDRomaniaFX
  | BREBankPolishGovtBondsAndTBills
  | BREBankFX
  | BMAndFBOVESPA
  | BancoSantanderChile
  | BancoSantanderBogota
  | BancoSantander
  | BancoSantanderCreditMarkets
  | BudapestStockExchange
  | BankofShanghaiCNYBonds
  | SumitomoMitsuiBankingCorporation
  | BancoSantanderAbbeyNationalTreasuryServiceFixedIncomeNotes
  | BancoSantanderStructuredProducts
  | BanestoEurobonds
  | BSXBermudaStockExchange
  | SarajevoStockExchange
  | BloombergTradebookFX
  | BTGPactualStructuredProducts
  | BTGPactualFX
  | BankofThailandTHBFXandMoneyMarketRates
  | BankofTokyoMitsubishiUFJVietnam
  | BulgarianStockExchangeAndBulgariaComposite
  | BucharestStockExchange
  | BarclaysCapitalUSExoticProducts
  | CIMBSecuritiesMYRDeposits
  | CaracasStockExchangeFixedIncome
  | TunisStockExchangeBonds
  | BolsadeValoresdePanamaFixedIncome
  | BruneiDarussalam
  | BarclaysCapitalThailandGovernmentBond
  | BarclaysCapitalJapaneseGovernmentBonds
  | BarclaysCapitalEuropeanCorporates
  | BarclaysCapitalExoticProducts
  | BarclaysCapitalInvestorSolutions
  | BarclaysCapitalAustralia
  | BarclaysCapitalPreciousMetals
  | BarclaysCapitalEquityIndex
  | Burgundy
  | BrazilComposite
  | CantorFitzgeraldAgencies
  | CreditAgricoleCIBSpotForwardAndDepositRates
  | CreditAgricoleCIBShanghaiCNYFXAndOnshoreInterestRateSwaps
  | CreditAgricoleCIBSecondaryCDOMarketAndCreditLinkedNotes
  | CreditAgricoleCIBUSDandEURDepositRates
  | CreditAgricoleCIBEURDepositRates
  | CreditAgricoleCIBEgyptEGPCrossAndInterbankRates
  | CreditAgricoleCIBFiduciaryDeposits
  | CreditAgricoleCIBIndicative
  | CreditAgricoleCIBFXOptionVolatilities
  | CasablancaStockExchange
  | ASXAustralianSecuritiesExchangeCombinedSession
  | CreditAgricoleCIBThailand
  | BondSpot
  | CreditAgricoleCIBUSTreasuries
  | ColombiaComposite
  | CommonwealthBankofAustraliaAUDCorporateBonds
  | CommonwealthBankofAustraliaInflationlinkedBonds
  | CommonwealthBankofAustraliaDepositRates
  | CommonwealthBankofAustraliaFX
  | CommonwealthBankofAustraliaSpotAndCrossRates
  | CompositeBloombergBondTrader
  | Commerzbank
  | ChinaBondGovernmentSecuritiesDepositorySettlementPrices
  | CommerzbankConvertibleBonds
  | DeutscheBankJapaneseConvertibleBonds
  | CentralBankofEgyptCentralBankCorridorRates
  | CBOEFuturesExchange
  | BarclaysCapitalEgypt
  | CitigroupJakartaIDRBonds
  | CommerzbankMiscellaneousBondsAndSpotsSwapsFixingsAndDeposits
  | CommerzbankFixedIncome
  | CommerzbankPreciousMetals
  | CommerzbankFrankfurt
  | CommerzbankFiduciaryDeposits
  | CentralBankofMaltaGovernmentBonds
  | CentralBankofBahrain
  | CBOEChicagoBoardOptionsExchange
  | CentralBankofIndia
  | CentralBankofJordanFXRates
  | CentralBankofKuwaitFXRates
  | CentralBankofQatarFXRates
  | TheCentralBankoftheRussianFederation
  | CloseBrotherSeydlerAGFrankfurtMain
  | CentralBankofSriLanka
  | CommerzbankForwards
  | CBTChicagoBoardofTradePitSession
  | CitigroupTaiwanGovernmentBonds
  | BCVCentralBankofVenezuelaBonds
  | Dexia
  | ChinaConstructionBankCNYBonds
  | ChinaConstructionBankOnshoreIRSFXFRA
  | ChinaBondGovernmentSecuritiesDepositoryCBCBondPrices
  | CBTChicagoBoardofTradeCombinedSession
  | CCILTheClearingCorporationofIndiaSpotCrossRates
  | CCILTheClearingCorporationofIndiaDeposits
  | CMEChicagoMercantileExchangeCombinedSession
  | ConduitCapitalMarkets
  | ContinentalCapitalMarketsDigitalIndicativePrices
  | ContinentalCapitalLiveBrokingPrices
  | ContinentalCapitalMarketsPrivatePlacement
  | CMXComexdivisionofNYMEXCombinedSession
  | CCOCentralJapanCommodityExchange
  | BVCBolsadeValoresdeColombiaFixedIncome
  | CCXChicagoClimateFuturesExchange
  | CitigroupCzechRepublicLocalBillsAndBonds
  | ChinaDevelopmentBankCNYOnshoreIRSCSFXFXVolatilities
  | CanDeal
  | BVCBolsadeValoresdeColombiaDerivatives
  | BolsaElectronicadeChile
  | CETIPRequestforQuotesModule
  | CreditEuropeBankNV
  | CEGHCentralEuropeanGasHubDerivativesMarketData
  | CelfinCapitalLatAmCorporates
  | CelfinCapitalBonds
  | CreditEuropeBankNVRONFXRates
  | CanadianNationalStockExchange
  | CitigroupHKStructuredNotes
  | CantorFitzgeraldTreasuryInsideMarks
  | CFCStanbicBankGovernmentBonds
  | CantorFitzgeraldHongKong
  | CFETSChinaForeignExchangeTradeSystemOTC
  | CFETSChinaForeignExchangeTradeSystemSpotQuote
  | CFETSChinaForeignExchangeTradeSystemOutrightRepoNetPrice
  | CFFChinaFinancialFutureExchange
  | CFGGroupCasablanceStockExchangeIndices
  | CommerzbankCertificates
  | CantorFitzgeraldUSTreasuries
  | CFETSChinaForeignExchangeTradeSystemCNYFXAndIRS
  | ShanghaiStockExchange
  | CitigroupNewYorkBankDepositRates
  | CitigroupLondonBranchDepositRates
  | CitigroupDeltaOne
  | CitigroupIndonesiaTreasuryBonds
  | CitigroupJPNGovernmentBonds
  | CitigroupCountryBonds
  | CitigroupMalaysiaTreasuryBonds
  | CitigroupCitiMarketsFX
  | CitigroupPolandTreasuryBonds
  | CitigroupIsraelTreasuryBonds
  | CitigroupRussiaTreasuryBonds
  | CitigroupCorporateBonds
  | Citigroup
  | CitigroupStructuredProducts
  | ChinaComposite
  | CFETSChinaForeignExchangeTradeSystemChineseBonds
  | CFETSChinaForeignExchangeTradeSystemTradePrice
  | CFETSChinaForeignExchangeTradeSystemCashBondQuotePrice
  | ChinatrustCommercialBankTWGovernmentBondsAndFX
  | PostalSavingsBankofChinaFX
  | ChileComposite
  | CitigroupBuenosAires
  | CitigroupArgentinianCentralBankBills
  | CIBCWorldMarketsCADForwardRates
  | CIMBSecuritiesGovernmentRecapBonds
  | CitigroupSofia
  | CIBCWorldMarketsFixedIncome
  | CICCreditIndustrieletCommercialEuroMediumTermNotes
  | CitigroupCostaRicanDebt
  | CitigroupDominicanRepublicFXandFixedIncome
  | CitigroupDubaiFX
  | CitigroupCairoFXandFixedIncome
  | CreditSuisseInflationLinkedProducts
  | CitigroupFXStreaming
  | CitigroupHKFX
  | CitigroupKazakhstan
  | CitigroupLatAm
  | CIMBSecuritiesKualaLumpur
  | CIMDCorretajeeInformacionMonetariaydeDivisasMadridSpanishGovtBondsTBillsDepoRatesFRAs
  | CIMBSecuritiesMYROptionVolatilities
  | CitigroupJapanDepositRates
  | CIMBSecuritiesGovernmentBonds
  | CIMBSecuritiesTHBGovernmentBondsandSwaps
  | INGEquityDerivativesandFX
  | ChinaBondInterbankBondsValuationPrices
  | ChinaBondInterbankBondsRecommendedValuationPrices
  | CitigroupPanama
  | CitigroupColomboSriLankaFXandFixedIncome
  | ChinaCITICBank
  | CitigroupMumbaiINRFixedIncome
  | CitigroupJamaicaFixedIncome
  | CitigroupMumbaiIndiaGovernmentBonds
  | CitigroupMoscowRUBFX
  | CitigroupPragueCZKFX
  | CitigroupUkraineFXandFixedIncome
  | CitigroupUruguayFXandFixedIncome
  | PureTrading
  | OSEOsakaSecuritiesExchangeCombinedSession
  | TSETokyoStockExchangeCombinedSession
  | PragueStockExchange
  | KCBKansasCityBoardofTradeCombinedSession
  | KFEKoreaStockExchangeCombinedSession
  | CarlKliem
  | CreditAgricoleCIBParis
  | CreditAgricoleCIBINRFixedIncomeAndCurrencyRates
  | CreditAgricoleCIBTWDSwapsAndMoneyMarketRates
  | CreditSuisseNassau
  | MontrealExchange
  | MBAMercadoaTerminodeBuenosAiresCombinedSession
  | CMEChicagoMercantileExchangePitSession
  | ChinaBondGovernmentSecuritiesDepositoryCMBKBondPrices
  | ChinaMerchantsBankCNYBonds
  | MGEMinneapolisGrainExchangeCombinedSession
  | CMIBCommercialInternationalBank
  | CompositeLondon
  | CompositeNewYork
  | CompositeTokyo
  | ComdaqMetals
  | CommerzbankRussianFX
  | ChinaBondGovernmentSecuritiesDepositoryMNSHBondPrices
  | MTSEuroCredit
  | CMXComexdivisionofNYMEXPitSession
  | CanadaComposite
  | PTBankCIMBNiagaFX
  | ChinaMerchantsBankBenchmarkBondsAndFX
  | CantorFitzgeraldMoneyMarketAndCorporateETrading
  | BGCantorMarketData
  | NYBICEIntercontinentalExchangeCombinedSession
  | NYMNewYorkMercantileExchangeCombinedSession
  | CommerzbankStructuredProductsAndFXStreaming
  | JPMorganChaseBogota
  | TaiwanOTCExchangeComparativeMarketBondPrice
  | ChinaBondOtherPlaceTradedBondsValuationPrices
  | ChinaBondOtherPlaceTradedBondsRecommendedValuationPrices
  | NASDAQOMXCopenhagen
  | BolsaNacionaldeValoresCostaRica
  | Cosmorex
  | CzechRepublicComposite
  | BolsaNacionaldeValoresCostaRicaFixedIncome
  | CredemLuxembourg
  | CitigroupRomaniaFixedIncomeAndFX
  | CreditSuisseMumbaiFX
  | CRTCapitalGroup
  | ShenzhenStockExchange
  | CreditSuisseGlobalConvertibleAndAsiaExchangeableBonds
  | CreditSuisseAsianFX
  | CreditSuissePhilippineGlobalBonds
  | CreditSuisseAustralianGovernmentBonds
  | CreditSuisseBrazil
  | CyprusStockExchange
  | CreditSuisseEmergingMarkets
  | CreditSuisseNewYork
  | ASXTrade24CombinedSession
  | CreditSuisseGovernmentBonds
  | CreditSuisseFXPricing
  | CreditSuisseHK
  | ChinaSecurityIndexCo
  | CreditSuisseLatAmFX
  | CreditSuisseMexicoLocalBonds
  | ChinaBondShanghaiExchangeTradedBondsValuationPrices
  | CSOBCeskoslovenskaObchodniBanka
  | ChinaBondShanghaiExchangeTradedBondsRecommendedValuationPrices
  | CeskoslovenskaObchodnaBankaSKKIRSRepoRates
  | CeskaSporitelna
  | CreditSuisseCHFForeignandDomesticBonds
  | ConseqInvestmetManagement
  | CreditSuisseMoscow
  | CreditSuisseSingapore
  | CreditSuisseSecondaryPricingUSRetailNotes
  | CreditSuisseStructuredNotes
  | CreditSuisseTRLFX
  | CreditSuisse
  | CreditSuisseZurich
  | CreditSuisseZurichFixedIncome
  | TorontoStockExchange
  | CitigroupChinaCNYBonds
  | TokyoCommodityExchangeCombinedSession
  | ThailandFuturesExchangeCombinedSession
  | CitigroupTelAvivIsraelBillsandBonds
  | CitigroupGlobalEquityLinkedNotes
  | CitigroupUSTreasuryBonds
  | CitigroupGuatemalaFXandFixedIncome
  | ChinaCITICBankCNYFX
  | ChinaCiticBankCNYBonds
  | CitigroupFXProducts
  | CitigroupJamaicaFX
  | CitigroupPeruPeruvianGovernmentBonds
  | CitigroupLondonDepositRates
  | CitigroupTelAvivFX
  | CitigroupKarachiPakistanFXandFixedIncome
  | ChinaBondOTCBondsRecommendedValuationPrices
  | CitigroupTaiwanMoneyMarketRates
  | CitigroupCzechRepublic
  | CitigroupSingaporeSGDFX
  | CitigroupShanghaiFXandFixedIncome
  | ICBPIIstitutoCentraledelleBanchePopolariItalianeSpA
  | CitigroupTunisFX
  | CitigroupTanzaniaGovernmentBondsAndFX
  | CitigroupVietmanFX
  | CookIslands
  | CentralBankoftheUAECDRatesandAEDSwaps
  | TSXVentureExchange
  | CFETSChinaForeignExchangeTradeSystemCashBondTradeYield
  | CFETSChinaForeignExchangeTradeSystemCashBondQuoteYield
  | CroatiaComposite
  | ChinaBondShenzhenExchangeTradedBondsValuationPrices
  | ChinaBondShenzhenExchangeTradedBondsRecommendedValuationPrices
  | DeutscheBankAsiaHighYieldBonds
  | DaiwaSecuritiesCapitalMarketsElectronicTrading
  | DaiwaSecuritiesCapitalMarketsAgencyDebt
  | DaiwaCapitalMarketsUSBills
  | DeutscheBankJakarta
  | DaiwaSecuritiesCapitalMarketsJGB
  | DubaiFinancialMarket
  | DeutscheBankAsia
  | DeutscheBankFixedIncomeIndices
  | DeutscheBank
  | DeutscheBankKualaLumpurMYRFXandMoneyMarketRates
  | DeutscheBankBangkokTHBSwapRates
  | DeutscheBankIndia
  | DeutscheBankBrazil
  | DeutscheBankStructuredNotes
  | DeutscheBankChile
  | DeutscheBankSriLanka
  | DeutscheBankGlobalEquityDerivatives
  | DeutscheBankStructuredEquitylinkednotes
  | DanskeBankAutoExecution
  | CommerzbankSpotsSwapsFixingsAndDeposits
  | DeutscheBankFX
  | DeutscheBankUSLondonAndBrazilStructuredNotes
  | DeutscheBankVietnamCurrencyProducts
  | DeutscheBankLatAmLocalBonds
  | DeutscheBankLuxembourg
  | DeutscheBankFiduciaryDeposits
  | DeutscheBankMalaysiaMYRFX
  | DeutscheBankPHPOnshoreSpotAndForwards
  | DeutscheBankMoscow
  | DeutscheBankMexico
  | DeutscheBankSingapore
  | DBSBankIndia
  | DeutscheBankPeru
  | DeutscheBankPakistan
  | DBSBankSingapore
  | DeutscheBankTHBFX
  | DBSBankTaiwan
  | DeutscheBankILSGovernmentBondsAndFX
  | DeutscheBankTaiwan
  | DenmarkCompositeNASDAQOMXCopenhagen
  | DeriviumCapital
  | DalianCommodityExchange
  | BankofAmericaMerrillLynchBasisOISAndFWDSwaps
  | DanskOTC
  | DanskeBank
  | BorsaItalianaDDMExcludingBlockTrades
  | DoualaStockExchange
  | DeutscheBankVietnamGovernmentBonds
  | DexiaEurobonds
  | DexiaBelgianStructuredProducts
  | DexiaBelgianTreasuryBills
  | NASDAQOMXFirstNorthCopenhagen
  | DeutscheBankFXForwardsMajors
  | DexiaFiduciaryDeposits
  | DeutscheBankSpotFixingRates
  | DFMDubaiFinancialMarket
  | NASDAQDubai
  | DubaiGoldandCommoditiesExchange
  | DekaBank
  | AbuDhabiSecuritiesExchange
  | DowJones
  | DowJonesSTOXX
  | CommerzbankStructuredCreditNotes
  | DMEDubaiMercantileExchangePitSession
  | DanskeBankFX
  | DeutscheBankSecuritizedEquityDerivativeProducts
  | DeutscheBankAustralianGovernmentAgencyBonds
  | DanskeBankLithuaniaGovernmentBonds
  | UnitedKingdomDebtManagementOffice
  | MTSDenmark
  | DNBBank
  | DNBBankSingapore
  | DNBBankasVilnius
  | DanskeBankLithuaniaFixedIncome
  | DeutschePostbank
  | CX2CanadaVenture
  | DeutscheBankJapaneseAgencyandMunicipalBonds
  | CX2CanadaToronto
  | DatatecChile
  | ChiXCanadaVentureExchange
  | ChinaDevelopmentBankCNYBonds
  | DaiwaCapitalMarketsGlobalConvertibleBonds
  | DaiwaCapitalMarketsKorea
  | TurquoiseEquityFutures
  | DZBankSingaporeAsianCorporateBonds
  | NYSEEuronextEquityIndices
  | ASXAustralianSecuritiesExchangeElectronicSession
  | ASX24ElectronicSession
  | BATSEurope
  | ChinaEverbrightBankDirectFeed
  | BGCPartnersEmergingMarketsEurobonds
  | EmiratesNBDGCCandMiddleEastProducts
  | BMFBrazilianMercantileandFuturesExchangeElectronicSession
  | BloombergEBond
  | BNPParibaseTrading
  | EBSRates
  | EBSFX
  | EgyptianExchange
  | MittelCorporeateFinance
  | CBTChicagoBoardofTradeElectronicSession
  | CMEChicagoMercantileExchangeElectronicSession
  | EuropeanCreditManagement
  | CMXComexdivisionofNYMEXElectronicSession
  | StandardAndPoors
  | EcuadorComposite
  | DMEDubaiMercantileExchangeElectronicSession
  | EuropeanEnergyDerivativesExchange
  | EuropeanEnergyExchange
  | EFGHermes
  | EFGHermesShamalNotes
  | BolsadeValoresdeGuayaquil
  | GreenXGreenExchangeElectronicSession
  | GFIGroupSukukBonds
  | TFS
  | HongKongExchangesandClearingElectronicSession
  | NileStockExchange
  | OSEOsakaSecuritiesExchangeElectronicSession
  | TSETokyoStockExchangeElectronicSession
  | EasternCaribbeanSecuritiesExchangeStKitts
  | KansasCityBoardofTradeElectronicSession
  | KFEKoreaStockExchangeElectronicSession
  | ElixirSecurities
  | ELXFutures
  | MBAMercadoaTerminodeBuenosAiresElectronicSession
  | EmporikiBankSpotCrossForwardAndDeposit
  | EMIDOvernightLargeLargerThan100M
  | MGEMinneapolisGrainExchangeElectronicSession
  | EMIDOvernightRegularLessThan100M
  | MTSEuro
  | EmiratesNBDmainlyforG7products
  | NYBICEIntercontinentalExchangeElectronicSession
  | NYLNYSEEuronextLiffeUSElectronicSession
  | NewYorkMercantileExchangeElectronicSession
  | NYSELIFFEParisDerivatives
  | NYSEEuronextLIFFEEquityIndices
  | GoldmanSachsAsia
  | BolsadeValoresdeQuito
  | EurexBondPrices
  | EdmondDeRothschildFinancialServices
  | ErsteGroupFixedIncome
  | ErisExchange
  | ErsteGroupCroatiaHRKFX
  | ASXTrade24ElectronicSession
  | SGXSingaporeStockExchangeElectronicSession
  | NasdaqOMXTallinn
  | TCMTokyoCommodityExchangeElectronicSession
  | ThailandFuturesExchangeElectronicSession
  | IShares
  | EuroTLX
  | EuropeComposite
  | EurexGermanyDerivatives
  | EurexSwitzerlandDerivatives
  | ChinaEverbrightBankFeedviaChinaForeignExchangeTradeSystem
  | ExaneParisMiscellaneousCurrencyBonds
  | ExcoNusantaraIndonesia
  | ExotixLtd
  | EgyptComposite
  | BloombergGenericPricing0000FixNYtime
  | BloombergGenericPricing0030FixNYtime
  | BloombergGenericPricing0100FixNYtime
  | BloombergGenericPricing0130FixNYtime
  | BloombergGenericPricing0200FixNYtime
  | BloombergGenericPricing0230FixNYtime
  | BloombergGenericPricing0300FixNYtime
  | BloombergGenericPricing0330FixNYtime
  | BloombergGenericPricing0400FixNYtime
  | BloombergGenericPricing0430FixNYtime
  | BloombergGenericPricing0500FixNYtime
  | BloombergGenericPricing0530FixNYtime
  | BloombergGenericPricing0600FixNYtime
  | BloombergGenericPricing0630FixNYtime
  | BloombergGenericPricing0700FixNYtime
  | BloombergGenericPricing0730FixNYtime
  | BloombergGenericPricing0800FixNYtime
  | BloombergGenericPricing0830FixNYtime
  | BloombergGenericPricing0900FixNYtime
  | BloombergGenericPricing0930FixNYtime
  | BloombergGenericPricing1000FixNYtime
  | BloombergGenericPricing1030FixNYtime
  | BloombergGenericPricing1100FixNYtime
  | BloombergGenericPricing1130FixNYtime
  | BloombergGenericPricing1200FixNYtime
  | BloombergGenericPricing1230FixNYtime
  | BloombergGenericPricing1300FixNYtime
  | BloombergGenericPricing1330FixNYtime
  | BloombergGenericPricing1400FixNYtime
  | BloombergGenericPricing1430FixNYtime
  | BloombergGenericPricing1500FixNYtime
  | BloombergGenericPricing1530FixNYtime
  | BloombergGenericPricing1600FixNYtime
  | BloombergGenericPricing1630FixNYtime
  | BloombergGenericPricing1700FixNYtime
  | BloombergGenericPricing1730FixNYtime
  | BloombergGenericPricing1800FixNYtime
  | BloombergGenericPricing1830FixNYtime
  | BloombergGenericPricing1900FixNYtime
  | BloombergGenericPricing1930FixNYtime
  | BloombergGenericPricing2000FixNYtime
  | BloombergGenericPricing2030FixNYtime
  | BloombergGenericPricing2100FixNYtime
  | BloombergGenericPricing2130FixNYtime
  | BloombergGenericPricing2200FixNYtime
  | BloombergGenericPricing2230FixNYtime
  | BloombergGenericPricing2300FixNYtime
  | BloombergGenericPricing2330FixNYtime
  | FaysalBankFX
  | FubonSecuritiesTaipeiTaiwanFX
  | Finansbank
  | FTSEBursaMalaysiaIndex
  | ICAPSouthAfrica
  | NASDAQOMXFirstNorthHelsinki
  | FinlandCompositeNASDAQOMXHelsinki
  | SecurityBankManilaPHPCorporateBonds
  | FIMMDAFixedIncomeMoneyMarketAndDerivativesAssociationofIndiaEndofDayValuation
  | FIMMDAFixedIncomeMoneyMarketAndDerivativesAssociationofIndiaTradedData
  | FinancialMarketsDealersAssociationNGNFixedIncome
  | FMSWertpapiermanagement
  | MTSFrance
  | NYSEEuronextParis
  | BMAndFBovespaNetSettlementTPlus1ReferencePrice
  | FishPool
  | SCOACHFrankfurt
  | SouthPacificStockExchange
  | FTSESETIndex
  | FTSEItaliaIndex
  | FTSEJSE
  | FTNFinancial
  | FTSEJFEAfricaAfricaIndex
  | FTSESTIndex
  | FTSEIndices
  | TAIFEXTaiwanFuturesExchange
  | BMAndFBovespaGrossSettlementTPlus0TradePrice
  | BMAndFBovespaTSettlement
  | BMAndFBovespaNetSettlementTPlus1TradePrice
  | SocieteGeneraleFXRates
  | GXGMarkets
  | GreeceCompositeAthensExchange
  | ICAPNorthAmericaInc
  | ICAPAustralia
  | BerlinStockExchange
  | GBOTGlobalBoardofTradeMauritius
  | BerlinBremenStockExchange
  | RBSUSBondsbyMaturity
  | GCRCapitalGmbH
  | DÃ¼sseldorfStockExchange
  | GovernmentDebtManagementAgencyHungary
  | XetraEuropeanStars
  | RBSMarketplace
  | MorganStanleyNY
  | UnitedKingdomDebtManagementOfficeGemmaPricing
  | GreenXGreenExchange
  | FrankfurtStockExchange
  | GFIColombiaFX
  | GFIGroupFX
  | GFIGroupFixedIncome
  | GFIGroupLondon
  | GFIGroupChile
  | GFIGroupEuroAndDomesticConvertibleBonds
  | GFIGroupEurobonds
  | GeorgiaStockExchange
  | HamburgStockExchange
  | HannoverStockExchange
  | NASDAQGlobalIndexDataServices
  | XetraInternationalMarket
  | BolsadeValoresNacionalGuatemala
  | MunichStockExchange
  | GMEGestoredeiMercatiEnergetici
  | MTSGermany
  | GhanaStockExchange
  | GoldmanSachs
  | GreTaiSecuritiesMarketOTCQuoteYield
  | GovPXICAP
  | XetraUSStars
  | GermanyComposite
  | StuttgartStockExchange
  | GoldmanSachsAsiaConvertibleBonds
  | GoldmanSachsCNHFX
  | GoldmanSachsUSCorporateBonds
  | GoldmanSachsUSConvertibleBonds
  | GoldmanSachsUSIndices
  | GoldmanSachsEmergingMarkets
  | GoldmanSachsEquityIndices
  | GoldmanSachsLatAmBonds
  | GoldmanSachsLatinAmericanEmergingMarkets
  | GoldmanSachsSecuritizedDerivatives
  | GoldmanSachsStructuredNotes
  | GoldmanSachsTokyo
  | XetraETFAndIndices
  | GreTaiSecuritiesMarketOTCBondPrice
  | GreTaiSecuritiesMarketOTCBondYield
  | GreTaiSecuritiesMarketOTCBondBestBidAskYield
  | GreTaiSecuritiesMarketOTCBondVolumeWeightedAverageYield
  | GreTaiSecuritiesMarketOTCBondTheoreticalPrice
  | ChannelIslandsStockExchange
  | GuyButler
  | GovPXICAP3PMEndofDay
  | GovPXICAP4PMEndofDay
  | GovPXICAP5PMEndofDay
  | StuttgartStockExchangeEUWAX
  | Xetra
  | HangSengBankChina
  | HanoiStockExchangeAutomatedPrice
  | HanoiStockExchangeNegotiatedPrice
  | HSBCBankBrazil
  | HabibBankPakistanFixedIncomeAndFX
  | HSBCUSAgencies
  | KAndHBank
  | HochiminhStockExchange
  | NASDAQOMXHelsinkiFixedIncome
  | HelabaLandesbankHessenThuringen
  | HongKongExchangesandClearing
  | HongKongExchangesandClearingFuturesandOptions
  | HongKongMercantileExchange
  | HongKongMonetaryAuthority1130Price
  | HongKongMonetaryAuthority1630Closing
  | HSBCIndia
  | SocieteGeneraleGroup
  | HSBCSingapore
  | HongLeongBank
  | HongLeongBankSGDCorporateBonds
  | HiMTF
  | HiMTFQuoteDriven
  | HiMTFOrderDriven
  | MTSFinland
  | HSBCAUDBonds
  | HSBC
  | HSBCAsianLEPOsAndEMEANotes
  | HSBCBankArgentina
  | HSBCSecuritiesUSA
  | HangSengBankChinaCNYFX
  | HSBCHKFX
  | HSBCBankUSAChile
  | HSBCIndicative
  | HSBCETrading
  | HSBCEquityDerivatives
  | HSBCSecuritiesEmergingMarkets
  | HSBCEgyptianBonds
  | HSBCStructuredFunds
  | HotspotFX
  | HSBCFixedIncome
  | HangSengBank
  | HangSengBankIndices
  | HSBCInternalPrices
  | HSBCTreasuryAndCapitalMarkets
  | HSBCBankUSA
  | HSBCUKStreaming
  | HSBCBankMexico
  | HSBCPanamaFixedIncome
  | HSBCBank
  | HSBCStructuredCreditProducts
  | HSBCStructuredRate
  | HSBCStructuredInvestments
  | HSBCTurkey
  | HSBCLondon
  | HSBCUruguay
  | HSBCVietnam
  | HSBCFXVolatilities
  | UniCreditBankHypoVereinsbank
  | UniCreditBankSerbia
  | UniCreditBankHongKong
  | UniCreditBankHungary
  | UniCreditLuxembourg
  | HanwhaSecuritiesKoreaFX
  | ICAPGermanyFixedIncomeAndFX
  | BombayStockExchange
  | GruppoBancarioIccrea
  | IndustrialBankChinaFX
  | ChiXEuropeccCFD
  | ICAPAPACFXSpotsAndForwards
  | ICAPAsiaPacFX
  | ICAPAsiaPacMoneyMarkets
  | CFETSChinaForeignExchangeTradeSystemICAPChina
  | ICAPAPANCNHProducts
  | ICAPEnergy
  | IndustrialandCommercialBankofChina
  | ICBCAsiaLtd
  | ICAPColombia
  | ICAPCanadianDollarForwards
  | SIFICAPChile
  | ICEIntercontinentalExchangeFuturesEurope
  | ICAPFixedIncome
  | NASDAQOMXIceland
  | ICAPGlobalFX
  | ICAPHongKong
  | PTICAPIndonesia
  | ICAPIndiaPrivateLtd
  | CitigroupIsraelFX
  | ICAPEMEAMoneyMarkets
  | ICAPNewZealandFXForwards
  | ICAPPhilippines
  | ICAPNewZealand
  | ICAPRONBonds
  | ICAPUS
  | IndonesiaCommodityAndDerivativesExchange
  | IrishStockExchange
  | PerhimpunanPedagangSuratUtangNegaraEndofDayFixing
  | PerhimpunanPedagangSuratUtangNegaraMidDayFixing
  | BankDBSIndonesia
  | BorsaItalianaAfterHours
  | INGFiduciaryDepos
  | IFEXInternationalFloatingRateNoteExchangeTassWertpapierhandelsbank
  | ICAPGlobalFXCurrencyOptions
  | MCXStockExchange
  | INGTaiwan
  | HSBCFX
  | ICAPIRDEMEAInterestRateDerivatives
  | IndonesiaStockExchange
  | ILSBrokers
  | ItalyCompositeBorsaItaliana
  | UniCreditBankRussia
  | BancaIMIFixedIncome
  | BancaIMIAutoExecution
  | BancaIMICertificatesAndIMIissues
  | IstanbulStockExchangeFixedIncome
  | MTSIreland
  | IndiaComposite
  | INGRomania
  | IndustrialBankFixedIncome
  | ChinaBondGovernmentSecuritiesDepositoryICBCBondPrices
  | IndustrialBankCo
  | INGCorporateBonds
  | INGBudapest
  | INGUkraine
  | INGEurasia
  | INGEurasiaRUBCorporateBonds
  | INGSingapore
  | INGUkraineUAHFX
  | INGPhilipines
  | InvestecBankFixedIncomeAndFX
  | INGSeoul
  | InvestecBankGlobalDepositRates
  | IndianCommodityExchange
  | INGSingaporeAsiaCredit
  | IsleofMan
  | IntiPrebonMoneyBorkers
  | IraqStockExchange
  | NASDAQOMXIcelandAndIcelandComposite
  | NationalStockExchangeofIndia
  | TurkiyeIsBankasi
  | IstanbulStockExchangeFixedIncomeLargeMarket
  | IstanbulStockExchangeFixedIncomeSmallMarket
  | IstanbulStockExchangeFixedIncomeLargeMarketT0
  | IstanbulStockExchangeFixedIncomeLargeMarketT1
  | Islandbanki
  | ISMCapitalCorporateBonds
  | IntesaSanpaoloIreland
  | IstanbulStockExchangeFixedIncomeRetailT0Large
  | IstanbulStockExchangeFixedIncomeRetailT1Large
  | IstanbulStockExchangeSmallMarketT0
  | IstanbulStockExchangeSmallMarketT1
  | IstanbulStockExchangeWholesaleTPlus0Large
  | IstanbulStockExchangeWholesaleTPlus1Large
  | TelAvivStockExchange
  | BancoItau
  | BancoItauChile
  | InvestecBankUK
  | ChiXEurope
  | IBoxxLimitedEuroConsolidatedPrices
  | IBoxxLimitedSterlingConsolidatedPrices
  | IstanbulStockExchangeLargeTPlus1Yield
  | IsInvestmentSecurities
  | IstanbulStockExchangeSmallTPlus1Yield
  | JamaicaStockExchange
  | JPMorganArgentina
  | JointBalticMarket
  | JPMorganChaseLondon
  | JPMorganChaseCheyneCreditSPINotes
  | Kabucom
  | SBIJapannext
  | JefferiesInternational
  | FukuokaStockExchange
  | TokyoAIM
  | JapanBondTradingCompanyJGB
  | ChiXJapan
  | JPMorganChaseIntrinsic
  | JASDAQOffExchange
  | JPMorganLatinAmericaUSDBonds
  | JPMorganChaseChina
  | JPMorganIndonesia
  | NagoyaStockExchange
  | OsakaSecuritiesExchange
  | JapanComposite
  | JPMorganChaseBankBangkok
  | JPMorganAsia
  | JPMorganAustralia
  | JPMorganInternal
  | JPMorganStructuredProducts
  | JPMorganLondonAutoExecution
  | JPMorganLondon
  | JPMorganFXComposite
  | JPMorganCorporateBonds
  | JPMorganInflationLinkedBonds
  | JPMorganSecuritiesNY
  | JPMorganWM
  | JPMorganSecuritiesAsiaPacificEquityDerivatives
  | JPMorganQuote
  | JPMorganChase
  | JPMorganNYAutoExecution
  | JPMorganMumbai
  | JASDAQOffExchangeCB
  | JPMorganChaseBankSingapore
  | JPMorgan
  | JPMorganTreasuries
  | JASDAQ
  | AmmanStockExchange
  | SapporoSecuritiesExchange
  | JSBank
  | JSGlobalCapital
  | JapanSecuritiesDealersAssociationMidYield
  | JapanSecuritiesDealersAssociationMidPrice
  | JASDAQIndices
  | TokyoStockExchange
  | SBIJapannextXMarket
  | JPMorganChaseBankUruguay
  | JerseyEquityFunds
  | AktieTorget
  | KazakhstanStockExchangeMorningSession
  | KazakhstanStockExchangeDaySession
  | KazakhstanStockExchangeEveningSession
  | KazakhstanStockExchange
  | Kasikornbank
  | KBCBankDepositRates
  | KBCBank
  | KBLKredietbankLuxembourgStructuredProducts
  | KasikornbankTHBSpotandFWDRates
  | KredytBank
  | KoreaBondPricingPrice
  | KoreaBondPricingYield
  | KansasCityBoardofTradePitSession
  | SouthKoreaComposite
  | KCBTCBOTSpreads
  | KoreaDevelopmentBank
  | KONEX
  | KempenAndCo
  | KoreaFreeboard
  | KFEKoreaStockExchangePitSession
  | KBCBankFiduciaryDeposits
  | KfWBankengruppe
  | CambodiaSecuritiesExchange
  | KASBSecurities
  | KoreaInvestmentAndSecurities
  | KiwoomcomSecurities
  | KuwaitStockExchange
  | PragueStockExchangeBlock
  | KoreaMoneyBrokerageCorporationBidAskforNonDealers
  | KoreaMoneyBrokerageCorporationBidAskforDealers
  | KoreaMoneyBrokerageCorporationTradedforDealers
  | KoreaMoneyBrokerageCorporationTradedforNonDealers
  | KCBTMGESpreads
  | NairobiSecuritiesExchange
  | KoreaExchange
  | KomercniBankaSocieteGeneraleGroup
  | KoreaExchangeIndexOptions
  | KOSDAQ
  | SeoulMoneyBrokerageServicesBidAskforNonDealers
  | SeoulMoneyBrokerageServicesTradedforNonDealers
  | BloombergKSBMMatrix
  | KoreaSecuritiesDealersAssociation
  | KoreaFinancialInvestmentAssociationPrice
  | KoreaFinancialInvestmentAssociationRealTime
  | KoreaFinancialInvestmentAssociationYield
  | KoreaExchangeYield
  | KoreaExchangePrice
  | CaymanIslandStockExchange
  | Landsbankinn
  | LandesbankBerlin
  | LandesbankBerlinEURDeposits
  | LBBWLandesbankBadenWÃ¼rttemberg
  | BanqueLBLuxSA
  | LBBWLandesbankBadenWÃ¼rttembergFiduciaryDeposits
  | NYSEEuronextLondon
  | TurquoiseDerivatives
  | LiechtensteinComposite
  | LloydsTSBBankFiduciaryRates
  | NASDAQOMXRiga
  | NASDAQOMXVilnius
  | LondonInternationalCompositeLondonInternational
  | NYSELiffeLondon
  | LjubljanaStockExchange
  | LloydsInternal
  | LloydsBank
  | LMELondonMetalExchangeComposite
  | TullettPrebonLatinAmericaMarker
  | LondonStockExchange
  | LSEEuropeanQS
  | LopezLeonBrokers
  | BGCLiquidezDTVM
  | LatviaComposite
  | LaosSecuritiesExchange
  | LloydsFXVolatilities
  | LuxembourgStockExchange
  | LloydsBankGilts
  | MacedonianStockExchange
  | MacquarieAustralia
  | MercadoAbiertoElectronicoUSDRepresentativePricing
  | MercadoAbiertoElectronicoalltypesofprices
  | MercadoAbiertoElectronicoUSDStandardPricing
  | ElMercadoAbiertoElectronico
  | MercadoAbiertoElectronicoARSStandardPricing
  | MercadoAbiertoElectronicoRepresentativeUSDAndARSPricing
  | MercadoAbiertoElectronicoARSRepresentativePricing
  | TwentyPercentMarktoMarketonPDSTreasuryReferenceRateAM
  | MonetaryAuthorityofSingapore
  | MauritiusStockExchange
  | MalayanBankingBerhadMaybank
  | MoldovaStockExchange
  | MBAMercadoaTerminodeBuenosAiresPitSession
  | MBALazard
  | MaybankBerhad
  | MartinBrokersEmergingMarkets
  | MartinBrokers
  | MuslimCommercialBank
  | MontrealClimateExchange
  | MultiCommodityExchangeofIndia
  | MGECBOTSpreads
  | MICEXMoscowInterbankCurrencyExchangeDerivatives
  | MercadoMexicanodeDerivados
  | BursaMalaysiaDerivatives
  | MontenegroStockExchange
  | Mediobanca
  | MercadodeFuturosdelAceitedeOliva
  | MizuhoCorporateBankBangkok
  | MeffRentaVariable
  | MeffPower
  | MGEMinneapolisGrainExchangePitSession
  | MizuhoCorporateBank
  | MizuhoInternationalConvertibles
  | MICEXMoscowInterbankCurrencyExchangeCompositeCorporateBonds
  | MICEXMoscowInterbankCurrencyExchange
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedDeals
  | MICEXMoscowInterbankCurrencyExchangeCompositeGovernmentBondsPrice
  | MICEXMoscowInterbankCurrencyExchangeGovernmentHighYield
  | MICEXMoscowInterbankCurrencyExchangeCompositeGovernmentBondsYield
  | MirabaudFinanzas
  | FTSE
  | MitsubishiUFJSecuritiesJGBBonds
  | BursaMalaysia
  | MKBHungarianForeignTradeBank
  | MKBRomexterraBank
  | MerrillLynchCanada
  | MerrillLynchJapanSecuritiesAgencyAndLocalGovernmentBonds
  | MerrillLynch
  | MerrillLynchEquityLinkedProducts
  | MerrillLynchLondon
  | MaltaStockExchange
  | MerrillLynchCurrency
  | MerrillLynchAsiaPacificLtdHongKong
  | MerrillLynchHoustonPx
  | MerrillLynchFIIdx
  | BankofAmericaMerrillLynchTokyo
  | MerrillLynchNYLatinAmericanRates
  | MerrillLynchNY
  | MerrillLynchStructuredProducts
  | MexicanStockExchange
  | MICEXMoscowInterbankCurrencyExchangeMainCorporateBondsPrice
  | MICEXMoscowInterbankCurrencyExchangeMainCorporateBondsYield
  | MICEXMoscowInterbankCurrencyExchangeMainGovernmentBondsPrice
  | MICEXMoscowInterbankCurrencyExchangeMainGovernmentBondsYield
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedCorporateBondsPrice
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedCorporateBondsYield
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedGovernmentBondsPrice
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedGovernmentBondsYield
  | MongolianStockExchange
  | MICEXMoscowInterbankCurrencyExchangeIndices
  | StockExchangeofMauritius
  | MPSCapitalServices
  | MacquarieFXVolatilities
  | MacquarieSingapore
  | MacquarieBank
  | MorganStanleyAsiaStructuredProducts
  | MorganStanleyJapanAutoExecution
  | MSCIBarra
  | MorganStanleyLondon
  | MorganStanleyBrazil
  | MorganStanleyAndCo
  | MorganStanleyEquityCertificates
  | MorganStanley
  | MontrealExchangeDerivatives
  | MorganStanleyEM
  | MorganStanleyFXForwards
  | MorganStanleyForeignExchange
  | MorganStanleyAsia
  | MorganStanleyIndicativePriceStructuredProducts
  | MorganStanleyMUFJ
  | MorganStanleyIndices
  | MorganStanleyMunicipalStructuredProducts
  | MorganStanleyMoscow
  | MorganStanleyNonDeliverableForwards
  | MorganStanleyUSTreasuries
  | MorganStanleyStructuredCreditProducts
  | MorganStanleyStructuredCommodities
  | MorganStanleyLondonFixedIncomeAndFX
  | MorganStanleyMUFGSecurities
  | MorganStanleyEquityDerivatives
  | TOMTheOrderMachineMTFAmsterdam
  | MeitanTradition
  | MTSSpA
  | MTSAustria
  | MTSGreece
  | MTSIsrael
  | NewEuroMTS
  | MTSPoland
  | MTSSlovenia
  | MTSCzechRepublic
  | BankofTokyoMitsubishiUFJFXVolatilities
  | MitsubishiUFJSecuritiesInternationalConvertibleBonds
  | MitsubishiUFJSecuritiesYenBonds
  | MitsubishiUFJSecuritiesInternationalBonds
  | MitsubishiUFJSecuritiesInflationBonds
  | MitsubishiUFJMerrillLynchPBSecurities
  | MitsubishiUFJSecuritiesBonds
  | MitsubishiUFJSecuritiesUSAInc
  | MitsubishiUFJSecuritiesInternationalUSTreasuries
  | MercadodeValoresdeMendoza
  | MalawiStockExchange
  | MSCIIndices
  | MorganStanleyMSCIIndices
  | MaputoStockExchange
  | MizuhoSecuritiesCoCDO
  | MizuhoInvestorSecurities
  | MizuhoInternationalNonJPYBonds
  | MizuhoInternational
  | MizuhoSecuritiesCoJPNGovtAndAgencyBonds
  | MizuhoSecuritiesCoAssetBackedSecurities
  | N2EXUKPowerExchange
  | NYSEEuronextAmsterdam
  | EuronextLIFFEDerivatives
  | NationalAustraliaBank
  | NationalAustraliaBankMelbourne
  | NationalAustraliaBankLondon
  | NairobiStockExchange
  | NationalBankofAbuDhabiUAE
  | NationalBankofAbuDhabiEgypt
  | NationalBankFXVolatilities
  | EmiratesNBD
  | NationalBankofEgypt
  | NationalBankofCanada
  | NomuraBPICleanPrice
  | NationalBankofPakistan
  | BolsadeValoresdeNicaragua
  | ChinaBondGovernmentSecuritiesDepositoryNJBKBondPrices
  | PakistanMercantileExchange
  | NikkoCitigroup
  | SMBCNikkoSecurities
  | NikkoCitigroupAgencyBonds
  | TraditionNonDeliverableForward
  | NordLBNorddeutscheLandesbankLondon
  | NYMEXDMESpreads
  | ReserveBankofIndiaRealTime
  | ReserveBankofIndiaOddLotMarket
  | NordeaStructuredBonds
  | RBIReserveBankofIndiaWhenIssuedMarket
  | NationalCommodityAndDerivativesExchangeIndia
  | TaiwanOTCExhcnageNegotiatedMarketBondPrice
  | NASDAQOMXFuturesExchange
  | NomuraMiddleEastAndNorthAfricaFX
  | NomuraFXRates
  | NordicGrowthMarket
  | NYSEGlobalIndexFeed
  | NagoyaStockExchangeConvertibleBonds
  | NIBBank
  | NepalStockExchange
  | NigerianStockExchange
  | NordLBNorddeutscheLandesbank
  | NLXNASDAQLondonExchange
  | NomuraInternationalLondonStructuredProducts
  | NomuraSecuritiesJapanAgencyBonds
  | NomuraSecuritiesJapanJGB
  | NomuraSecuritiesJapanFXOptionVolatilities
  | NomuraSecurities
  | NomuraSingapore
  | OsloStockExchangeAndNorwayComposite
  | NordLB
  | NomuraSecuritiesLatinAmericanFX
  | NomuraSecuritiesNYBonds
  | NomuraFixedIncomeSecurities
  | NomuraInternationalLondon
  | NomuraSecuritiesNYUSTreasuryAndAgency
  | Nordea
  | NomuraSecuritiesJapanStructuredProducts
  | NomuraSecuritiesUSDStructuredNotes
  | NASDAQOMXCommodities
  | NICEPricingServicesPrice
  | NICEPricingServicesYield
  | NASDAQOMXCopenhagenStructuredProducts
  | NASDAQOMXHelsinkiStructuredProducts
  | NASDAQOMXStockholmStructuredProducts
  | NYSEArcaEurope
  | NorwayOTC
  | NikkeiIndices
  | NetherlandsAntilles
  | NittanCapitalAsia
  | NatixisNY
  | BankofNovaScotiaGovernmentandCorporateBonds
  | NamibianStockExchange
  | NomuraSecuritiesJapanCDO
  | NatixisDepositRates
  | NatixisAutoExecution
  | NatixisEmergingMarketBonds
  | NatixisEquityDerivatives
  | NatixisFiduciaryRates
  | Natixis
  | NatixisMoneyMarketFundRates
  | NatixisNewYork
  | NatixisOptionVolatility
  | NYBICEIntercontinentalExchangePitSession
  | NykreditBankGovernmentBonds
  | NYSEBondMatch
  | NykreditBank
  | NewYorkMercantileExchangePitSession
  | NewZealandStockExchangeAndNewZealandComposite
  | NewZealandFinancialMarketsAssociation
  | NewZealandFinancialMarketsAssociationBondFixings
  | NewZealandStockExchangeDerivatives
  | OneChicago
  | OCBCOverseaChineseBankingCorp
  | OCBCBankMalaysiaBerhad
  | OCBCOverseaChineseBankingCorpFXOptionVolatilities
  | OCBCOverseaChineseBankingCorpFXOptionVolatilitiesTier2
  | OCBCOverseaChineseBankingCorpKualaLumpur
  | ODEOsakaDojimaCommodityExchange
  | MuscatSecuritiesMarket
  | IberianEnergyDerivativesExchange
  | NASDAQOMXIndices
  | MorganStanleyOPALS
  | OPRA
  | OCBCOverseaChineseBankCorp
  | OsakaStockExchangeCurrencyFutures
  | OsakaSecuritiesExchangeCB
  | NordicABMAllTradesLevel1Data
  | NordicABMLevel1And2Data
  | NordicABMYield
  | BolsadeComerciodeSantiagodeChileOTCChileanPeso
  | PFTSStockExchangeOrderDriven
  | PakistanComposite
  | BTGPactualFixedIncome
  | BVPASABolsadeValoresyProductosdeAsuncionEndofDayPYG
  | BNPParibasConvertibleBonds
  | DeutschePfandbriefbank
  | JefferiesBache
  | TullettPrebonInformationFX
  | CitigroupCitiTradingStrategies
  | BTGPactualAutoExecution
  | PhilippinesDealingAndExchangeCorpCorporateBoardSummary
  | PhilippinesDealingAndExchangeCorpFixedIncomeBoardSummary
  | PhilippinesDealingAndExchangeCorpBestBidFixing
  | PhilippinesDealingAndExchangeCorpMorningFixing
  | PhilippinesDealingAndExchangeCorpAfternoonFixing
  | LimaStockExchange
  | PFTSStockExchange
  | PioneerCorretoradeCambio
  | BankIndonesia
  | KarachiStockExchange
  | BankPekaoUnicreditGroup
  | NYSEEuronextLisbon
  | PLUSStockExchangePlc
  | PhilippineStockExchange
  | NASDAQOMXStockholm
  | MTSPortugal
  | BolsadeValoresyProductosdeAsuncion
  | BolsadeValoresdePanama
  | Powernext
  | PohjolaBank
  | OTCMarkets
  | TullettPrebonUSDInterestRateSwapsAndFRAs
  | PragueStockExchangeFutures
  | VALMERValuacionOperativayReferenciasdeMercadocontributedprice
  | PalestineExchange
  | BancoSantanderBrazil
  | PostalSavingsBankofChina
  | PingAnTradition
  | PublicBankBerhad
  | PolandCompositeWarsawStockExchange
  | PEXPrivateExchange
  | PowerExchangeCentralEurope
  | TullettPrebonDealingRates
  | TullettPrebonSouthAfrica
  | QatarNationalBank
  | QatarExchange
  | BolsadeQuito
  | QuoteMTF
  | QatarStockExchange
  | PFTSStockExchangeQuoteDriven
  | RaiffeisenBankAlbania
  | RaboSecurities
  | RaboBank
  | RZBRaiffeisenZentralbankPoland
  | RabobankInternational
  | RabobankCredit
  | RZBRaiffeisenZentralbankBucharest
  | RaiffeisenSwitzerland
  | ReserveBankofAustralia
  | RBSUSAgencies
  | RZBRaiffeisenZentralbankBulgaria
  | RZBRaiffeisenZentralbankBulgarianFloatersAndEurobonds
  | RaboBankBrazil
  | RBCRoyalBankofCanadaDominion
  | RBCRoyalBankofCanada
  | RBCRoyalBankofCanadaLondon
  | RBCRoyalBankofCanadaCapitalMarketsLondon
  | RBCRoyalBankofCanadaCapitalMarkets
  | RBSEquityDerivatives
  | RBCRoyalBankofCanadaCapitalMarketsUSTreasury
  | RBCRoyalBankofCanadaCapitalMarketsEuropeanGovernmentBonds
  | RBCRoyalBankofCanadaMultiProduct
  | RBCRoyalBankofCanadaUSTreasuryRBHTPricing
  | RBCRoyalBankofCanadaUSTreasuryRBHUPricing
  | RBCRoyalBankofCanadaUSTreasuryRBHVPricing
  | RaiffeisenAustria
  | RaiffeisenBankInternational
  | ReserveBankofIndia
  | RabobankTokyo
  | RBSMalaysia
  | RBSLatinAmericaInterestRateandFXDerivatives
  | RobobankOffshoreNonDeliverableForward
  | RBSNVDepositRates
  | RBSUSTreasuriesandAgencies
  | RBSLondon
  | RBSRoybalBankofScotlandFinancialMarkets
  | RBSSecuritiesTokyo
  | RBSRoybalBankofScotland
  | RBSFiXSpot
  | RBSMarketplaceLatinAmerica
  | RBSThailand
  | RBCRoyalBankofCanadaUSTreasury
  | RBSValuations
  | RabobankLondon
  | RZBRaiffeisenZentralbankCroatia
  | PragueStockExchangeRMSystem
  | RaiffeisenCentrobank
  | RizalCommercialBankingCorp
  | RenaissanceBJMSecurities
  | RenaissanceCapital
  | RenaissanceCapitalMoscow
  | Renascenca
  | BankRepublicSocieteGeneraleGroup
  | NASDAQOMXFirstNorthIceland
  | RaiffeisenBankFX
  | RosarioFuturesExchange
  | RussellGlobalStyleIndices
  | RHBBankBerhad
  | RHBBankBerhadThailand
  | RZBRaiffeisenZentralbankFixedIncomePricing
  | MICEXMoscowInterbankCurrencyExchangeAndRussiaComposite
  | RBSMediumTermNotes
  | MICEXMoscowInterbankCurrencyExchangeNegotiatedMarket
  | RomaniaComposite
  | Robeco
  | MICEXMoscowInterbankCurrencyExchangeRepoMarket
  | RASDAQ
  | RTSRussianTradingSystem
  | RBSRomania
  | RBSWholesaleMarket
  | RBSChina
  | RTSRussianTradingSystemDerivatives
  | RTSRussianTradingSystemsMoney
  | RTSRussianTradingSystemComposite
  | CajaRuralCastellon
  | RussellIndices
  | RusselIndices
  | RwandaStockExchange
  | MICEXMoscowInterbankCurrencyExchangeMainMarket
  | RBCRoyalBankofCanadaSpreads
  | Riyadbank
  | RBCRoyalBankofCanadaAustralia
  | RBCRoyalBankofCanadaCapitalMarketsIRSSwapPricing
  | SIBEXEquityMarket
  | RaiffeisenBank
  | SigmaX
  | ValenciaStockExchange
  | SouthAfricanCapitalMarketBrokers
  | SouthAfricanFuturesExchange
  | JohannesburgStockExchangeDerivatives
  | SIACSecuritiesIndustryAutomationCorpAMEX1
  | BancoSantanderNY
  | BarcelonaStockExchange
  | StandardCharteredBankSouthAfrica
  | SaudiBritishBank
  | StandardBankBrazil
  | ScotiaBankChile
  | ScotiaBankCostaRica
  | UBSZurich
  | StandardBankLondon
  | StandardBank
  | StandardCharteredBankBrazil
  | StandardBankSouthAfrica
  | StateBankofVietnam
  | ScotiaCapitalUSAgency
  | StandardCharteredBankAsiaFXRates
  | StandardCharteredBankHongKong
  | StandardCharteredBankJakarta
  | StandardCharteredBankMalaysia
  | StandardCharteredBankShanghai
  | StandardCharteredBankChina
  | StandardCharteredFirstBankKorea
  | StandardCharteredBankSingapore
  | StandardCharteredForeignExchangeAutoExecution
  | ScotiaCapitalNYUSTreasury
  | StandardCharteredBankMumbai
  | StandardCharteredFX
  | StandardCharteredIndonesia
  | ScotiaCapitalCanadianGovernmentBonds
  | StandardCharteredBankDubai
  | StandardCharteredBankPhilippines
  | StandardCharteredBankManila
  | ScotiaCapitalPeru
  | StandardCharteredBankQatar
  | StandardCharteredBankThai
  | StandardCharteredBankTaiwan
  | StandardCharteredBankVietnam
  | SibiuFinancialandCommodityExchangeEquityfutures
  | SwazilandStockExchangeCommonStocks
  | ShenzhenDevelopmentBank
  | SIXSwissExchange
  | SEBSkandinaviskaEnskildaBankenETradeable
  | SEBSkandinaviskaEnskildaBanken
  | SEBSkandinaviskaEnskildaBankenMerchantBankingOslo
  | SEB
  | SEBSkandinaviskaEnskildaBankenMerchantBanking
  | SEBSkandinaviskaEnskildaBankenMerchantBankingCorporates
  | SEBSkandinaviskaEnskildaBankenLondon
  | SEBSkandinaviskaEnskildaBankenStockholmStructuredProducts
  | SecurityBankPhilippines
  | SistemaElectronicodeNegociacionColombiaPrice
  | SENAFSistemaElectronicodeNegociaciondeActivosFinancieros
  | SistemaElectronicodeNegociacionColombiaYield
  | BancoSantanderNYAutoExecution
  | SETFXSistemaElectronicodeTransacciondeMonedaExtranjeraCombined
  | SETFXSistemaElectronicodeTransacciondeMonedaExtranjeraSpotMarket
  | SETFXSistemaElectronicodeTransacciondeMonedaExtranjeraNextDayMarket
  | NASDAQOMXFirstNorthStockholm
  | ASXTrade24PitSession
  | BancoSantanderFrankfurtFiduciaryDeposits
  | SocieteGeneraleBrazil
  | SocieteGeneraleCorporates
  | SocieteGeneraleConvertibles
  | SocieteGeneraleEmergingMarkets
  | SocieteGeneraleIndicativePrices
  | SocieteGeneraleInterestRateDerivatives
  | SocieteGeneraleIndia
  | SocieteGeneraleMorocco
  | SocieteGeneraleFXOptionVolatilities
  | SocieteGenerale
  | SocieteGeneraleTaipeiBranch
  | SocieteGeneraleTreasuries
  | SocieteGeneraleUSTreasuriesandAgencies
  | SGXSingaporeStockExchangePitSession
  | SaudiHollandiBank
  | SHFEShanghaiFuturesExchange
  | ShanghaiStockExchangeFixedIncomePlatform
  | ShorcanBrokers
  | SIMVSE
  | SecuritiesIndustryAutomationCorporation
  | SibiuStockExchange
  | BancoSantanderMexcio
  | JohannesburgStockExchange
  | BratislavaStockExchange
  | SEBSkandinaviskaEnskildaBankenMerchantBankingKommuninvestBonds
  | ColomboStockExchange
  | SpainComposite
  | SeoulMoneyBrokerageServicesBidAskforDealers
  | SingaporeMercantileExchange
  | TullettPrebonSwapMarker
  | SumitomoMitsuiBankingCorporationBangkok
  | MTSSpain
  | MadridStockExchange
  | StifelNicolausCompanyRetail
  | SNetworkGlobalIndexes
  | StifelNicolausEurope
  | SENAFSistemaElectronicodeNegociaciondeActivosFinancierosYield
  | SNSBank
  | NYSENewYorkStockExchange
  | BilbaoStockExchange
  | SocieteGeneraleWarsaw
  | SocieteGeneraleWarsawSpots
  | SingaporeExchange
  | ShanghaiPudongDevelopmentBank
  | SAndPIndices
  | INGAmsterdam
  | StreetSoftware
  | StPetersburgInternationalMercantileExchange
  | BarcelonaStockExchangeContinuousMarket
  | BerneExchange
  | SEBMerchantBankingSweden
  | SwedenCompositeNASDAQOMXStockholm
  | CitigroupLondon
  | NASDAQOMXNordicExchangeStockholm
  | IndonesiaStockExchangePrice
  | IndonesiaStockExchangeYield
  | StateStreet
  | CitigroupNewYorkFixedIncome
  | StandardCharteredBankPakistan
  | StockholmStockExchange
  | StateStreetBank
  | StandardCharteredSriLanka
  | SierraLeoneStockExchange
  | SuperintendenciadeBancaSegurosyAFP
  | SvenskaHandelsbanken
  | SwitzerlandComposite
  | SwissExchangeAll
  | SIXSwissIndices
  | ScoachSwitzerland
  | DamascusSecuritiesExchange
  | SydbankFiduciaryDeposits
  | SydbankCurrencyForwards
  | Sydbank
  | SynesisFinanceSA
  | SeychellesSecuritiesExchange
  | AlphaTradingSystems
  | TadawulSaudiStockExchange
  | Takarekbank
  | TassWertpapierhandelsbank
  | TatraBankaAS
  | TatraBankaASGovernmentBonds
  | StockExchangeofThailand
  | ThaiBondMarketAssociationIndicativeData
  | ThaiBondMarketAssociationLastExecutedYield
  | ThaiBondMarketAssociationDelayedMarketYield
  | ThaiBondMarketAssociationLastExercisePrice
  | ThaiBondMarketAssociationReferenceYield
  | ThaiBondMarketAssociationWeightedAveragePrice
  | TurksandCaicosIslandsComposite
  | TCMTokyoCommodityExchangePitSession
  | TDSecuritiesNY
  | TDSecuritiesIndicativeAgencyOfferings
  | TDSecuritiesEletronicTrading
  | TDSecuritiesCanada
  | TraditionBogota
  | TDSecuritiesTokyo
  | TDSecurities
  | TurkEkonomiBankasiAS
  | ThailandFuturesExchangePitSession
  | TFSICAPFX
  | TraditionCredit
  | TraditionFinancialServices
  | TraditionFinancialServiciesTelAviv
  | TaipeiFubonBankDepositRates
  | TokyoFinancialExchange
  | OmegaATS
  | ThanachartBankPublicCompanyLtd
  | IstanbulStockExchange
  | INGTurkey
  | TMXSelect
  | Liquidnet
  | TURKDEXTurkishDerivativesExchange
  | TullettPrebon
  | TotanICAPPro
  | BancodeTokyoMitsubishiUFJBrasilSA
  | GibraltarComposite
  | TreasuryMarketsAssociationFixing
  | TMBBankPCL
  | BankofTokyoMitsubishiUFJThailandTHBTelegraphicTransferRates
  | BankofTokyoMitsubishiUFJThailandTHBSpotForwardandInterbankDepositRates
  | BankofTokyoMitsubishiUFJJakarta
  | TullettPrebonTreasuryMarker
  | BankofTokyoMitsubishiUFJHK
  | AlphaVenture
  | TheTokyoTanshiCo
  | GreTaiSecuritiesMarketBondLast5MinsTradePriceAverage
  | GreTaiSecuritiesMarketBondLastTradePrice
  | TrinidadandTobagoStockExchange
  | MarshallsBahrainMoneyMarketsForwards
  | MarshallsBahrainMoneyMarketsDeposits
  | TullettFFT
  | TullettPrebonFixedIncome
  | TaipeiForexTrade
  | TaipeiForexBidandAsk
  | TullettPrebonMoneyMarkets
  | TullettPrebonFXOVolatility
  | TullettPrebonSITICOChina
  | TullettPrebonGlobalForeignExchange
  | TullettPrebonSITICOChinaCNYMoneyMarketRates
  | TullettPrebonVolatility
  | Turquoise
  | TriActMATCHNowToronto
  | FINRATraceBondTradeDisseminationService
  | TraditionSwitzerland
  | RBSUKGiltsAndCorporates
  | RBSEuroCorporates
  | TraditionChile
  | TradeGate
  | TraditionUKIndicativePriceforEmergingMarketBonds
  | TraditionAsiaLtd
  | TraditionLuxembourg
  | HSBCTrinkaus
  | TraditionFinancialServicesPhilippines
  | TraditionUK
  | TraditionSouthAfrica
  | TraditionSingapore
  | TraditionStructuredProducts
  | TraditionUKSubscriptionData
  | LloydsTSBDepositRates
  | LloydsTSBFXOptionsVolatility
  | TorontoStockExchangeIndex
  | TaiwanCompositeTaiwanStockExchangeGreTaiSecuritiesMarket
  | TotanICAPMarkets
  | TunisStockExchangeAndTunisiaComposite
  | AndimaTunnelPrices
  | MICROmegaSecurities
  | TriActMATCHNowVenture
  | InstinetCanadaCross
  | ChiXCanada
  | DaresSalaamStockExchange
  | NYSEMKT
  | HSBCMiddleEast
  | NASDAQOMXBXformerlyBostonStockExchange
  | UBSAsia
  | UlaanbatarCityBankMarketSectorCurrency
  | UBSInvestmentBank
  | UBSEmergingMarkets
  | UBSHongKong
  | UBSLondonInflationPricing
  | UBSSecuritiesIndiaPrivateLtd
  | HVBMilanBranchUnicreditGroup
  | UBSAustraliaAutoExecutionBBT
  | UBSAGRussianBonds
  | UBSInvestmentBankAustralia
  | UBSFrankfurt
  | UBSSecurities
  | UBSUSAgencyBondPrice
  | UBSIndia
  | UBSFixedIncome
  | UBSTreasuries
  | UBSInvestmentBankZurich
  | NSXNationalStockExchange
  | UniCreditBulbank
  | UniCreditTiriacBank
  | FINRAAlternativeDisplayFacility
  | NASDAQInternational
  | UBSEuropeanGovernmentBonds
  | BATSTradingUS
  | UniCreditSpALondonBranch
  | UgandaSecuritiesExchange
  | UnitedArabEmiratesComposite
  | UBMUniCreditBancaMobiliareMilan
  | NASDAQTradeReportingFacility
  | UkrainianExchange
  | FTSE7dayindices
  | RTSUkrainianExchange
  | LondonStockExchangeORB
  | InternationaSecuritiesExchange
  | ChicagoStockExchange
  | MiamiInternational
  | UniCreditBankIreland
  | UnitedBankKarachi
  | UnitedOverseasBankSingaporeSGDSpot
  | UnitedOverseasBankSingaporeG7CurrenciesFXOptionVolatilities
  | UnitedOverseasBankMalaysiaTier2
  | UnitedOverseasBankSingaporeFXOptionVolatility
  | UnitedOverseasBankSingaporeTier2
  | UnitedOverseasBankKorea
  | UnitedOverseasBankMalaysia
  | UnitedOverseasBankIndonesia
  | UnitedOverseasBankSingapore
  | UnitedOverseasBankThailand
  | UnitedOverseasBankVietnam
  | UnitedOverseasBankSingaporeSGDCorporateBonds
  | NewYorkStockExchangeArca
  | UBSPriceImprovementNetworkFixedIncome
  | NASDAQOMXGlobalMarket
  | NASDAQCapitalMarket
  | USComposite
  | UnitedStockExchange
  | NASDAQOMXInterMarket
  | AxisBankMumbai
  | NASDAQOMXOTCBulletinBoard
  | NASDAQOTC
  | NASDAQGlobalSelectMarket
  | NASDAQOMXPSXformerlyPhiladelphiaStockExchange
  | BolsadeValoresdeMontevideo
  | UkraineCompositePFTSStockExchange
  | MizuhoUATRates
  | VALMERValuacionOperativayReferenciasdeMercadoPriceviafeed
  | VALMERValuacionOperativayReferenciasdeMercadoYieldviafeed
  | BolsaBolivianadeValores
  | VolksbankCZAS
  | SEBBankasLithuania
  | VenezuelaComposite
  | VolbrokerFixing
  | HanoiStockExchange
  | BritishVirginIslands
  | INGVysyaBank
  | EDGAExchange
  | EDGXExchange
  | VietnamComposite
  | VietnamBondMarketAssociation
  | BankVontobel
  | CapeVerdeStockExchange
  | CaracasStockExchange
  | HanoiUPCoM
  | SIXSwissExchangeEurope
  | BATSYExchange
  | INGVysyaIndiaFXRates
  | Wachovia
  | WestpacBankingCorp
  | WellsFagroSecuritiesBondsAndPreferreds
  | WestpacInstutionalBank
  | Westpac
  | ICEIntercontinentalExchangeFuturesCanada
  | UBSSingapore
  | NationalStockExchangeofIndiaFixedIncomeWholesaleMarket
  | UBSJapan
  | UBSLondon
  | WellsFargoSecurities
  | CIBCWorldMarketsCanadaGovts
  | CIBCWorldMarketsFX
  | WestLB
  | WestLBAGDepositRates
  | TheWMCompanySpotClosingRateswithouthistory
  | TheWMCompanyForwardClosingRateswithouthistory
  | TheWMCompanySpotClosingRateswithhistory
  | WallichAndMatthes
  | TheWMCompanyForwardIntradayRateswithhistory
  | WMCompanyIntradayNDFRates
  | TheWMCompanySpotIntradayRateswithhistory
  | WMCompanyClosingNDFRates
  | WarsawStockExchangeMTSPoland
  | GreTaiSecuritiesMarketBondVolumeWeightedAverageYield
  | WestpaceTrading
  | WarsawStockExchange
  | WellsFargoSecuritiesTreasuries
  | ViennaStockExchangeOTC
  | MarkitBOAT
  | ChiXOTC
  | NYSEEuronextOTC
  | XetraBonds
  | IrishStockExchangeOTC
  | NordicGrowthMarketOTC
  | BudapestStockExchangeOTC
  | BorsaItalianaOTC
  | LjubljanaStockExchangeOTC
  | OTCXBernerKantonalBank
  | LondonStockExchangeOTC
  | MorganStanleyFXStreamingC
  | OsloStockExchangeOTC
  | OMXOTC
  | PLUSStockExchangePlcOTC
  | ReutersOTC
  | AthensOTCStockExchange
  | BulgariaOTC
  | SIXSwissOffExchange
  | CyprusStockExchangeEmergingCompaniesMarket
  | YellowSheets
  | JohannesburgStockExchangeInterestRateMarketCentralOrderBook
  | JohannesburgStockExchangeInterestRateMarketDerivatives
  | ZagrebStockExchange
  | ZhengzhouCommodityExchange
  | SEBFXStreamingBY
  | FXStreamingDX
  | FXStreamingFY
  | StandardCharteredFXStreamingGY
  | StandardCharteredFXStreamingHY
  | FXStreamingIY
  | FXStreamingJY
  | FXStreamingKX
  | FXStreamingUY
  | FXStreamingVY
  | FXStreamingWX
  | StandardCharteredFXStreamingH
  | MorganStanleyFXStreamingK
  | MorganStanleyFXStreamingL
  | MorganStanleyFXStreamingM
  | FXStreamingR
  | ZimbabweStockExchange
  | ZÃ¼rcherKantonalbank
  | LusakaStockExchange
  deriving (Ord,Eq,Show,Read)
